# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Star' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Star
  pod 'Alamofire', '4.9.1'
  pod 'AlamofireImage'
  pod 'SwiftyJSON', '4.0.0'	
  pod 'Device', '~> 3.1.2'
  pod 'UIColor_Hex_Swift', '~> 5.1.0'

end
